# Classically Piloted Target-Task Training Data Collection Mission

# Mission, task, and controller configuration
mission                  = "maze"
task                     = 'maze'
endpoint_tolerance       = 10.0
max_endpoint_radius      = 50.0
min_blaze_gap            = 10.0
plot_update_period       = 0.5
plot_debug               = false
control_update_period = 0.7
drone_speed              = 0.5
voxel_size               = 1.0
occupancy_cache_size     = 100000
lookahead_distance       = 0.75
bogo_attempts            = 5000
num_repetitions          = 10
timeout                  = 30
autoKill                 = false
record                   = false

# ML model configuration
use_model  = false
seq_len    = 64
batch_size = 8
rnn_size   = 32

# Environment, simulation, and airsim configuration
image_shape                      = [256, 256, 3]
recording_dir                    = "C:/Users/MIT Driverless/Documents/AirSim"
recording_name_regex             = "^[0-9]+-[0-9]+-[0-9]+-[0-9]+-[0-9]+-[0-9]+$"
camera_field_of_view             = 0.3927 # pi/8 radians
camera_coordinate_offset         = [0.5, 0.0, -0.5]
world_to_unreal_coordinate_scale = 100

# Drone dynamics parameters