# Classically Piloted Target-Task Training Data Collection Mission

# Mission, task, and controller configuration
mission                  = "multitrack"
task                     = 'multitrack'
endpoint_tolerance       = 10.0
target_task_radius       = 15.0
max_endpoint_radius      = 15.0
plot_update_period       = 0.5
plot_debug               = false
control_update_period    = 0.1
max_speed                = 2.0
voxel_size               = 1.0
occupancy_cache_size     = 100000
lookahead_time           = 0.75
bogo_attempts            = 5000
num_repetitions          = 10
timeout                  = 30
autoKill                 = false
record                   = false
target_move_time         = 30
temporal_search_step     = 0.1

# ML model configuration
use_model  = false
seq_len    = 64
batch_size = 8
rnn_size   = 32

# Environment, simulation, and airsim configuration
image_shape                      = [256, 256, 3]
recording_dir                    = "C:/Users/MIT Driverless/Documents/AirSim"
recording_name_regex             = "^[0-9]+-[0-9]+-[0-9]+-[0-9]+-[0-9]+-[0-9]+$"
camera_field_of_view             = 0.1963 # pi/8 radians
camera_coordinate_offset         = [0.5, 0.0, -0.5]
world_to_unreal_coordinate_scale = 100

# Drone dynamics parameters