apiVersion: v1
kind: Pod
metadata:
  name: saturation
spec:
  containers:
    - name: train-container
      image: dolphonie1/causal_repo:0.1.17
      command:
        - "/bin/bash"
        - "-c" # run with bash and pass in the args below
      args:
        - "cd /src/drone_causality &&
        export DATASET_NAME=$(echo ${DRL_GPU_WORKER_ID} | sed 's/0/balcony/g; s/1/devens/g; s/2/both/g') &&
        export PYTHONPATH=\"${PYTHONPATH}:/src/drone_causality\" &&
        python analysis/perturb_trajectory.py \
        slurm/skipper/jobs/perturb/perturb_${DATASET_NAME}.json \
        /data/skipper/models/chair4_fine/train/params.json \
        saturation_perturbation \
        --output_prefix /data/skipper/visualization/perturb/saturation_${DATASET_NAME} \
        --deltas 0.5 1.5 2.5 3.25 \
        --distance_fxn final_distance \
        --perturb_frac 0.4 \
        --skip_models ctrnn_mixedcfc"