apiVersion: v1
kind: Pod
metadata:
  name: deepdrone-maze-neighborhood
spec:
  containers:
    - name: skipper-pod
      image: raminmh/deepdrone:latest
      command:
        - "/bin/bash"
        - "-c" # run with bash and pass in the args below
      args:
        - "python training.py \
        --model=lstm \
        --data_dir=/data/deepdrone/data/maze-neighborhood-parsed \
        --save_dir=/data/deepdrone/logs/maze-neighborhood \
        --history_dir=/data/deepdrone/history/maze-neighborhood"
