apiVersion: v1
kind: Pod
metadata:
  name: deepdrone-following-redwood-ncp
spec:
  containers:
    - name: skipper-pod
      image: raminmh/deepdrone:latest
      command:
        - "/bin/bash"
        - "-c" # run with bash and pass in the args below
      args:
        - "python training.py \
        --model=ncp \
        --data_dir=/data/deepdrone/data/following-redwood-parsed \
        --save_dir=/data/deepdrone/logs/following-redwood \
        --history_dir=/data/deepdrone/history/following-redwood"

