apiVersion: v1
kind: Pod
metadata:
  name: deepdrone-hiking-neighborhood-gru
spec:
  containers:
    - name: skipper-pod
      image: raminmh/deepdrone:latest
      command:
        - "/bin/bash"
        - "-c" # run with bash and pass in the args below
      args:
        - "python training.py \
        --model=gru \
        --data_dir=/data/deepdrone/data/hiking-neighborhood-parsed \
        --save_dir=/data/deepdrone/logs/hiking-neighborhood \
        --history_dir=/data/deepdrone/history/hiking-neighborhood"
