apiVersion: v1
kind: Pod
metadata:
  name: minicity-default
spec:
  containers:
    - name: skipper-pod
      image: mitdrl/deepdrone:minicity
      command:
        - "/bin/bash"
        - "-c"
      args:
        - "python tf_data_training.py"
