cp deepdrone-following-neighborhood-cnn-job.yaml     deepdrone-following-neighborhood-cnn-job-cpu.yaml
cp deepdrone-following-neighborhood-cnn-job.yaml     deepdrone-following-neighborhood-cnn-job-cpu.yaml
cp deepdrone-following-neighborhood-ctgru-job.yaml   deepdrone-following-neighborhood-ctgru-job-cpu.yaml
cp deepdrone-following-neighborhood-gru-job.yaml     deepdrone-following-neighborhood-gru-job-cpu.yaml
cp deepdrone-following-neighborhood-lstm-job.yaml    deepdrone-following-neighborhood-lstm-job-cpu.yaml
cp deepdrone-following-neighborhood-ncp-job.yaml     deepdrone-following-neighborhood-ncp-job-cpu.yaml
cp deepdrone-following-neighborhood-odernn-job.yaml  deepdrone-following-neighborhood-odernn-job-cpu.yaml
cp deepdrone-following-neighborhood-rnn-job.yaml     deepdrone-following-neighborhood-rnn-job-cpu.yaml
cp deepdrone-following-redwood-cnn-job.yaml          deepdrone-following-redwood-cnn-job-cpu.yaml
cp deepdrone-following-redwood-ctgru-job.yaml        deepdrone-following-redwood-ctgru-job-cpu.yaml
cp deepdrone-following-redwood-gru-job.yaml          deepdrone-following-redwood-gru-job-cpu.yaml
cp deepdrone-following-redwood-lstm-job.yaml         deepdrone-following-redwood-lstm-job-cpu.yaml
cp deepdrone-following-redwood-ncp-job.yaml          deepdrone-following-redwood-ncp-job-cpu.yaml
cp deepdrone-following-redwood-odernn-job.yaml       deepdrone-following-redwood-odernn-job-cpu.yaml
cp deepdrone-following-redwood-rnn-job.yaml          deepdrone-following-redwood-rnn-job-cpu.yaml
cp deepdrone-hiking-neighborhood-cnn-job.yaml        deepdrone-hiking-neighborhood-cnn-job-cpu.yaml
cp deepdrone-hiking-neighborhood-ctgru-job.yaml      deepdrone-hiking-neighborhood-ctgru-job-cpu.yaml
cp deepdrone-hiking-neighborhood-gru-job.yaml        deepdrone-hiking-neighborhood-gru-job-cpu.yaml
cp deepdrone-hiking-neighborhood-lstm-job.yaml       deepdrone-hiking-neighborhood-lstm-job-cpu.yaml
cp deepdrone-hiking-neighborhood-ncp-job.yaml        deepdrone-hiking-neighborhood-ncp-job-cpu.yaml
cp deepdrone-hiking-neighborhood-odernn-job.yaml     deepdrone-hiking-neighborhood-odernn-job-cpu.yaml
cp deepdrone-hiking-neighborhood-rnn-job.yaml        deepdrone-hiking-neighborhood-rnn-job-cpu.yaml
cp deepdrone-hiking-redwood-cnn-job.yaml             deepdrone-hiking-redwood-cnn-job-cpu.yaml
cp deepdrone-hiking-redwood-ctgru-job.yaml           deepdrone-hiking-redwood-ctgru-job-cpu.yaml
cp deepdrone-hiking-redwood-gru-job.yaml             deepdrone-hiking-redwood-gru-job-cpu.yaml
cp deepdrone-hiking-redwood-lstm-job.yaml            deepdrone-hiking-redwood-lstm-job-cpu.yaml
cp deepdrone-hiking-redwood-ncp-job.yaml             deepdrone-hiking-redwood-ncp-job-cpu.yaml
cp deepdrone-hiking-redwood-odernn-job.yaml          deepdrone-hiking-redwood-odernn-job-cpu.yaml
cp deepdrone-hiking-redwood-rnn-job.yaml             deepdrone-hiking-redwood-rnn-job-cpu.yaml
cp deepdrone-maze-neighborhood-cnn-job.yaml          deepdrone-maze-neighborhood-cnn-job-cpu.yaml
cp deepdrone-maze-neighborhood-ctgru-job.yaml        deepdrone-maze-neighborhood-ctgru-job-cpu.yaml
cp deepdrone-maze-neighborhood-gru-job.yaml          deepdrone-maze-neighborhood-gru-job-cpu.yaml
cp deepdrone-maze-neighborhood-lstm-job.yaml         deepdrone-maze-neighborhood-lstm-job-cpu.yaml
cp deepdrone-maze-neighborhood-ncp-job.yaml          deepdrone-maze-neighborhood-ncp-job-cpu.yaml
cp deepdrone-maze-neighborhood-odernn-job.yaml       deepdrone-maze-neighborhood-odernn-job-cpu.yaml
cp deepdrone-maze-neighborhood-rnn-job.yaml          deepdrone-maze-neighborhood-rnn-job-cpu.yaml
cp deepdrone-maze-redwood-cnn-job.yaml               deepdrone-maze-redwood-cnn-job-cpu.yaml
cp deepdrone-maze-redwood-ctgru-job.yaml             deepdrone-maze-redwood-ctgru-job-cpu.yaml
cp deepdrone-maze-redwood-gru-job.yaml               deepdrone-maze-redwood-gru-job-cpu.yaml
cp deepdrone-maze-redwood-lstm-job.yaml              deepdrone-maze-redwood-lstm-job-cpu.yaml
cp deepdrone-maze-redwood-ncp-job.yaml               deepdrone-maze-redwood-ncp-job-cpu.yaml
cp deepdrone-maze-redwood-odernn-job.yaml            deepdrone-maze-redwood-odernn-job-cpu.yaml
cp deepdrone-maze-redwood-rnn-job.yaml               deepdrone-maze-redwood-rnn-job-cpu.yaml
cp deepdrone-target-neighborhood-cnn-job.yaml        deepdrone-target-neighborhood-cnn-job-cpu.yaml
cp deepdrone-target-neighborhood-ctgru-job.yaml      deepdrone-target-neighborhood-ctgru-job-cpu.yaml
cp deepdrone-target-neighborhood-gru-job.yaml        deepdrone-target-neighborhood-gru-job-cpu.yaml
cp deepdrone-target-neighborhood-lstm-job.yaml       deepdrone-target-neighborhood-lstm-job-cpu.yaml
cp deepdrone-target-neighborhood-ncp-job.yaml        deepdrone-target-neighborhood-ncp-job-cpu.yaml
cp deepdrone-target-neighborhood-odernn-job.yaml     deepdrone-target-neighborhood-odernn-job-cpu.yaml
cp deepdrone-target-neighborhood-rnn-job.yaml        deepdrone-target-neighborhood-rnn-job-cpu.yaml
cp deepdrone-target-redwood-cnn-job.yaml             deepdrone-target-redwood-cnn-job-cpu.yaml
cp deepdrone-target-redwood-ctgru-job.yaml           deepdrone-target-redwood-ctgru-job-cpu.yaml
cp deepdrone-target-redwood-gru-job.yaml             deepdrone-target-redwood-gru-job-cpu.yaml
cp deepdrone-target-redwood-lstm-job.yaml            deepdrone-target-redwood-lstm-job-cpu.yaml
cp deepdrone-target-redwood-ncp-job.yaml             deepdrone-target-redwood-ncp-job-cpu.yaml
cp deepdrone-target-redwood-odernn-job.yaml          deepdrone-target-redwood-odernn-job-cpu.yaml
cp deepdrone-target-redwood-rnn-job.yaml             deepdrone-target-redwood-rnn-job-cpu.yaml
