apiVersion: v1
kind: Pod
metadata:
  name: deepdrone-target-redwood-cnn
spec:
  containers:
    - name: skipper-pod
      image: raminmh/deepdrone:latest
      command:
        - "/bin/bash"
        - "-c" # run with bash and pass in the args below
      args:
        - "python training.py \
        --model=cnn \
        --data_dir=/data/deepdrone/data/target-redwood-parsed \
        --save_dir=/data/deepdrone/logs/target-redwood \
        --history_dir=/data/deepdrone/history/target-redwood"

