# NCP Model Piloted Chase-Task Evaluation Mission

# Mission, task, and controller configuration
mission                  = "target_evaluation_ctgru"
task                     = "target"
endpoint_tolerance       = 5.0
target_task_radius       = 10.0
max_endpoint_radius      = 8.0
plot_update_period       = 0.5
plot_debug               = false
control_update_period    = 1.0
drone_speed              = 1.0
voxel_size               = 1.0
occupancy_cache_size     = 100000
lookahead_distance       = 2.25
bogo_attempts            = 5000
num_repetitions          = 100
timeout                  = 30
autoKill                 = true
record                   = false
fog                      = 0
rain                     = 0

# ML model configuration
use_model     = true
model_name    = 'gru'
model_weights = 'logs/target-redwood/ctgru-2021-03-21-13-22-05-rev=13.0-weights.025--0.8588.hdf5'
seq_len       = 64
batch_size    = 8
rnn_size      = 32

# Environment, simulation, and airsim configuration
image_shape                      = [256, 256, 3]
recording_dir                    = "C:/Users/MIT Driverless/Documents/AirSim"
recording_name_regex             = "^[0-9]+-[0-9]+-[0-9]+-[0-9]+-[0-9]+-[0-9]+$"
camera_field_of_view             = 0.3927 # pi/8 radians
camera_coordinate_offset         = [0.5, 0.0, -0.5]
world_to_unreal_coordinate_scale = 100

# Drone dynamics parameters