# NCP Model Piloted Target-Task Evaluation Mission

# Task and controller configuration
mission = "target_ncp"
endpointTolerance = 10.0
maxEndpointRadius= 15.0
minHikingBlazeGap = 10.0
plotUpdatePeriod = 0.5
controlUpdatePeriod = 0.7
droneSpeed = 0.5
voxelSize = 1.0
occupancyCacheSize = 100000
lookAheadDistance = 0.75
bogoAttempts = 5000
numRepetitions = 10

# ML model configuration
useModel = true
modelName = "ncp"
modelWeights = "model-checkpoints/ncp-2021-02-11-18-18-01-rev=12.0-weights.001--0.9028.hdf5"
sequenceLength = 64
batchSize = 8
rnnSize = 32

# Environment, simulation, and airsim configuration
imageShape = [256, 256, 3]
recordingDir = "C:/Users/MIT Driverless/Documents/AirSim"
recordingNameRegex = "^[0-9]+-[0-9]+-[0-9]+-[0-9]+-[0-9]+-[0-9]+$"
cameraFieldOfView = 0.3927 # pi/8 radians
cameraCoordinateOffset = [0.5, 0.0, -0.5]
worldToUnrealCoordinateScale = 100

# Drone dynamics parameters